spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/events_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 15
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false

logging:
  level:
    root: INFO
    com.example.cleanup: INFO

server:
  port: 8080

database-cleaner:
  allowed-date-time-columns:
    - public.events.created_at
    - public.events_double.created_at